#This file is used only for spring profile dev.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fittrackdb
    username: fittrack_admin
    password: adminStrongPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
