spring:
  application:
    name: fitTrack

  datasource:
    url: jdbc:postgresql://localhost:5432/fittrackdb
    username: postgresTest
    password: postgresTestPassword

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


sms:
  service:
    url: http://localhost:8081