spring:
  application:
    name: fitTrack

  datasource:
    url: jdbc:postgresql://localhost:5432/fittrackdb
    username: postgresTest
    password: postgresTestPassword

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect