spring:
  application:
    name: fitTrack

  datasource:
    url: jdbc:postgresql://localhost:5432/fittrackdb
    username: postgresTest
    password: postgresTestPassword

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

sms:
  service:
    url: http://localhost:8081
